server:
  port: 7777
spring:
  application:
    name: spring-cloud-config-client
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
