server:
  port: 7777
spring:
  application:
    name: spring-cloud-config-client
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
